import { type NextPage } from "next";
import Head from "next/head";

import { Header } from "~/components/Header";
import { NameFetchWizard } from "~/components/NameFetchWizard";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Name Fetch</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <NameFetchWizard />
      </main>
    </>
  );
};

export default Home;
